config/routes.rb
Seatyourself::Application.routes.draw do
  get "sessions/new"
  get "sessions/create"
  get "sessions/destroy"
  get "reservations/show"
  get "reservations/new"
  get "reservations/edit"
  get "reservations/index"
  get "users/new"
  get "users/create"
  resources :users, :only => [:new, :create, :index]
  resources :restaurants do
    resources :reservations
  end
  root "welcome#index"
  resources :sessions, :only => [:new, :create, :destroy]
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base

belongs_to :user
belongs_to :restaurant
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
	validates :location, :name, :presence => true
	has_many :reservations
	has_many :users, :through => :reservations
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	has_many :reservations
  	has_many :restaurants, :through => :reservations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   protect_from_forgery with: :exception

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_filter :load_product
  def show
  	@reservation = Reservation.find(params[:id])
  end

  def create
  	@reservation = @restaurant.reservations.build(reservation_params)
    @reservation.user_id = current_user.id
    if @reservation.save
      redirect_to restaurants_path, notice: 'Reservation created successfully'
    else
      render :action => :show
    end
  end

  def destroy
    @reservation = Reservation.find(params[:id])
    @reservation.destroy
  end

  private
  def reservation_params
    params.require(:reservation).permit(:restaurant_id, :user_id, :reservation_time)
  end

  def load_product
    @restaurant = Restaurant.find(params[:restaurant_id])
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
    if params[:search]
    	@restaurants = Restaurant.find(:all, :conditions =>['name LIKE ?', "%#{params[:search]}%"])
  	else
  		@restaurants = Restaurant.find(:all)
  	end
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    if current_user
    	@reservation = @restaurant.reservations.build
    end
  end

  def new
    @restaurant = Restaurant.new
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)

    if @restaurant.save
      redirect_to restaurants_url
    else
      render :new
    end
  end

  def update
    @restaurant = Restaurant.find(params[:id])

    if @restaurant.update_attributes(restaurant_params)
      redirect_to restaurant_path(@restaurant)
    else
      render :edit
    end
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
    redirect_to restaurants_path
  end

  private
  def restaurant_params
    params.require(:restaurant).permit(:name, :location)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to restaurants_url, :notice => "Logged in!"
    else
      flash.now[:alert] = "Invalid email or password"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to restaurants_url, :notice => "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  	    @users = User.all

  end

  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
    if @user.save
      redirect_to users_url, :notice => "Signed up!"
    else
      render "new"
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :name)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Seatyourself</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<% if flash[:notice] %>
      <p id="notice"><%= flash[:notice] %></p>
    <% end %>
    <% if flash[:alert] %>
      <p id="alert"><%= flash[:alert] %></p>
    <% end %>

<%= yield %>

<p class="userinfo">
      <% if current_user %>
        Signed in as <%= current_user.email %>. <%= link_to "Log out", session_path("current"), :method => :delete %>
      <% else %>
        <%= link_to "Log in", new_session_path %> or <%= link_to "Sign up", new_user_path %>
      <% end %>
    </p>

</body>
</html>

app/views/reservations/edit.html.erb
<h1>Reservations#edit</h1>
<p>Find me in app/views/reservations/edit.html.erb</p>

app/views/reservations/index.html.erb
<h1>Reservations#index</h1>
<p>Find me in app/views/reservations/index.html.erb</p>

app/views/reservations/new.html.erb
<h1>Reservations#new</h1>
<p>Find me in app/views/reservations/new.html.erb</p>

app/views/reservations/show.html.erb
<h1>Reservations#show</h1>
<p>Find me in app/views/reservations/show.html.erb</p>

app/views/restaurants/_form.html.erb
<%= form_for(@restaurant) do |f| %>
<% if @restaurant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

      <ul>
      <% @restaurant.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :location %><br />
    <%= f.select :location, [['Downtown', 'Downtown'], ['North End', 'North End'], ['East York', 'East York'], ['West End', 'West End'],['Scarborough', 'Scarborough']] %>
  </div>
  <th></th>
  <th></th>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Restaurants#edit</h1>
<p>Find me in app/views/restaurants/edit.html.erb</p>

app/views/restaurants/index.html.erb
<h1>Restaurants</h1>
<%= link_to "New Restaurant", "/restaurants/new" %>

<% @restaurants.each do |restaurant| %>
   <p> <%= restaurant.id %>		<%= restaurant.name %>		<%= restaurant.location %>		<%= link_to "Reserve", restaurant %></p>


<% end %>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>

<%= render 'form' %>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/show.html.erb
<% if current_user %>

  <h3>Reservations</h3>

  <p>Reservatoins for <%= @restaurant.name %></p>

  <% @restaurant.reservations.each do |reservation| %>
    <p>
      <%= reservation.reservation_time %>
      <br>
      <% if reservation.user != nil %>
        <em> by <%= reservation.user.email %></em>
        Added on: <%= reservation.created_at %>
      <% end %>
    </p>
  <% end %>
<h4>New Reservation</h4>

  <%= form_for([@restaurant, @reservation]) do |f| %>
    <% if @reservation.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

        <ul>
        <% @reservation.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :reservation_time %><br />
      <%= f.time_field :reservation_time %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>

<% else %>
  <p>Please <%= link_to "log in", new_session_path %> to add a reservation.</p>
<% end %>

app/views/users/index.html.erb
<h1>Users</h1>
<%= link_to "New User", "/users/new" %>

<% @users.each do |user| %>
   <p> <%= user.id %>		<%= user.name %>		<%=user.email %></p>
<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name %><br/>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br/>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br/>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br/>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit %></div>
<% end %>

app/views/welcome/index.html.erb
<h1>SeatYourself</h1>

<%= form_tag restaurants_path, :method => 'get' do %>
	<p>
		<%= label_tag "By Restaurant Name:" %>
		<%= text_field_tag :search %>
		<%= submit_tag "Find a Seat" %>
	</p>
<% end %>

<p><%= link_to "List of Restaurants", controller: "restaurants" %></p>